#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#define APP_CONTROL_PERIOD_MS              1U
#define APP_MECHANISM_PERIOD_MS            5U
#define APP_NAVIGATION_PERIOD_MS          10U
#define APP_SAFETY_PERIOD_MS              10U
#define APP_MONITOR_PERIOD_MS            100U

#define APP_CAN_RX_TASK_STACK_SIZE       1536U
#define APP_CONTROL_TASK_STACK_SIZE      2048U
#define APP_MECHANISM_TASK_STACK_SIZE    1536U
#define APP_SENSOR_TASK_STACK_SIZE       1536U
#define APP_NAVIGATION_TASK_STACK_SIZE   3072U
#define APP_COMM_TASK_STACK_SIZE         2048U
#define APP_SAFETY_TASK_STACK_SIZE       1024U
#define APP_MONITOR_TASK_STACK_SIZE      1024U

#endif /* CONTROL_CONFIG_H */
